#!/bin/bash

PATH=/bin:/sbin:/usr/bin:/usr/sbin

# Preinstall script for BabelColorCTA package to remove older
# installer folder(s) and packages due to renaming of folder
# introduced with v4.5.2 (November 2015). Otherwise these
# folder would stick around and likely cause confusion when
# searching/launching application.
#
# Developer had removed the ' (Intel)' or similar string
# from the folder name.

ls -1d /Applications/BabelColor*CT*A*[Ii]ntel* | while read appdir; do
	rm -fr "${appdir}"
done

exit 0

# Example env vars:
# DSTVOLUME=/
# DSTROOT=/
# USER=root
# SCRIPT_NAME=postinstall
# PATH=/bin:/sbin:/usr/bin:/usr/sbin
# INSTALL_PKG_SESSION_ID=com.babelcolor.BabelColorCTA
# LANG=en_US.UTF-8
# PACKAGE_PATH=/path/to/BabelColorCTA-4.2.0.pkg
